### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel azimuthStream)

### ISSUE THREAD

**Issue by djsliders** [ikkoyeah/compasstools#2]
Hi,

I am using the last version (0.1.0) of your plugin.
It is working great with Android but I got the following error on Ios:
`
The following MissingPluginException was thrown while activating platform stream on channel azimuthStream:
MissingPluginException(No implementation found for method listen on channel azimuthStream)
When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:519:29)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:505:64)
...
`

Do you know where it can come from?

flutter doctor: 
`[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-CH)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
`
Thank you for your work and your help !

**Comment by arsalanj** [comment]
@djsliders did you manage to resolve it?

**Comment by arsalanj** [comment]
I don't think there is complete implementation for iOS
